//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalUI1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Community : DbContext
    {
        public Community()
            : base("name=Community")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Complaint> Complaints { get; set; }
        public virtual DbSet<DashboardPost> DashboardPosts { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FriendsAndFamily> FriendsAndFamilies { get; set; }
        public virtual DbSet<HouseList> HouseLists { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Resident> Residents { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
    }
}
