//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalUI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ComplaintID { get; set; }
        public Nullable<int> ResidentID { get; set; }
        public string ComplaintRegarding { get; set; }
        public string ComplaintStatus { get; set; }
    
        public virtual Resident Resident { get; set; }
    }
}
