//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalUI1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int VisitorId { get; set; }
        public string VisitorName { get; set; }
        public string VisitorResaon { get; set; }
        public Nullable<System.DateTime> VisitStartTime { get; set; }
        public Nullable<System.DateTime> VisitorEndTime { get; set; }
        public int ResidentID { get; set; }
        public string VisitorEntryStatus { get; set; }
        public Nullable<int> VisitorApprovedBy { get; set; }
    
        public virtual Employee Employee1 { get; set; }
        public virtual Resident Resident { get; set; }
    }
}
